version: 2.1

jobs:
  getting-started:
    docker:
      - image: cimg/python:3.9
    steps:
      - run:
          environment:
            PYTHONPATH: ~/project/src
          working_directory: ~/project/src
          name: run tests
          command: python -m unittest

workflows:
  setup:
    jobs:
      - getting-started
